aws:
  region: us-east-1
  iam_instance_profile_arn: arn:aws:iam::471112568442:instance-profile/EC2
  hf_token_fp: /home/dh/DSAN/FMBench/hf_token.txt
  

run_steps:
    security_group_creation: yes
    key_pair_generation: yes
    deploy_ec2_instance: yes
    run_bash_script: yes
    delete_ec2_instance: yes

security_group:
    group_name: fmbench_orchestrator_sg
    description: MultiDeploy EC2 Security Group
    #If VPC Is left empty, boto3 automatically gets the default vpc for your region
    vpc_id:

key_pair_gen:
    #Need to change this name to something better?
    # This assumes that if key_pair_generation is false, you have the key pair stored in the root.
    # If so, change the file name to your KP name and the script will pick it up.
    key_pair_name: fmbench_orchestrator_kp
    key_pair_fpath: fmbench_orchestrator_kp.pem


# Neuron AMI : ami-05d498302130f9036
# DeepLearning AMI AL2 : ami-07f302d2a74e2b584
# Al2 AMI, CPU bench : ami-0e54eba7c51c234f6
# Take the below as list of dict as there might be 2 instances with the same AMI
instances:
  - instance_type: g5.2xlarge
    ami_id: ami-05c3e698bd0cffe7e
    device_name: /dev/sda1
    ebs_del_on_termination: True
    ebs_Iops: 16000
    ebs_VolumeSize: 250
    ebs_VolumeType: gp3
    startup_script: startup_scripts/gpu_ubuntu_startup.txt
    post_startup_script: post_startup_scripts/fmbench.txt
    fmbench_config: https://raw.githubusercontent.com/dheerajoruganty/multi-deploy-ec2/refs/heads/main/configs/config-ec2-llama3-8b.yml
  - instance_type: g5.2xlarge
    ami_id: ami-05c3e698bd0cffe7e
    device_name: /dev/sda1
    ebs_del_on_termination: True
    ebs_Iops: 16000
    ebs_VolumeSize: 250
    ebs_VolumeType: gp3
    startup_script: startup_scripts/gpu_ubuntu_startup.txt
    post_startup_script: post_startup_scripts/fmbench.txt
    fmbench_config: https://raw.githubusercontent.com/dheerajoruganty/multi-deploy-ec2/refs/heads/main/configs/config-ec2-llama3-8b.yml
  
  # - instance_type: t3.micro
  #   ami_id: ami-07f302d2a74e2b584
  #   startup_script: startup_scripts/az_linux2_startup.txt